Document: smplayer
Title: Debian smplayer Manual
Author: <insert document author here>
Abstract: This manual describes what smplayer is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/smplayer/smplayer.sgml.gz

Format: postscript
Files: /usr/share/doc/smplayer/smplayer.ps.gz

Format: text
Files: /usr/share/doc/smplayer/smplayer.text.gz

Format: HTML
Index: /usr/share/doc/smplayer/html/index.html
Files: /usr/share/doc/smplayer/html/*.html

  
